INSERT INTO "department" ("id") VALUES
	('Accounting'),
	('Agricultural Economics and Extension'),
	('Animal Science'),
	('Biochemistry'),
	('Business Administration'),
	('Business Education'),
	('Christian Religious Studies'),
	('Educational Planning and Administration'),
	('English Language Education'),
	('English Studies'),
	('Finance'),
	('French and Foreign Studies'),
	('Guidance and Counseling'),
	('History and International Studies'),
	('Information Resources Management'),
	('Information Technology'),
	('Medical Laboratory Science'),
	('Medicine'),
	('Microbiology'),
	('Music'),
	('Nursing'),
	('Physiology'),
	('Political Science'),
	('Social Work and Human Services')
ON CONFLICT ("id") DO NOTHING;
